### ISSUE TITLE
ACF Input Field Not Displaying

### ISSUE THREAD

**Issue by mbar001** [solepixel/wp-multiple-passwords#10]
Hello!

I have everything set up correctly, but the input field is not being displayed. Latest versions of WP and ACF. Thank you for the assistance!

[image](https://user-images.githubusercontent.com/44042390/46772502-464f6780-ccc6-11e8-8586-1b573de1055e.png)

![image](https://user-images.githubusercontent.com/44042390/46772557-8ca4c680-ccc6-11e8-854b-d2d6318f6cfb.png)

**Comment by solepixel** [comment]
It appears that the textarea was not displaying for ACF (Free). I have updated the code to resolve this issue. Please download the latest version (1.1.1) for the fix. Thanks for letting me know and sorry for the delay!
