### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jokew** [solepixel/wp-multiple-passwords#2]
Hi

Your plugin looks exactly like something I need. I need to restrict a form on page with +500 passwords. But i'm having some trouble installing the plugin.

First I installed the ACF Plugin, even the one from your account here. So when creating a page with password I insert a password in the top right corner (which is originally from Wordpress). After that I selected the extra meta box 'Additional Passwords'. I copied a few passwords in there but the don't work on the page.. What am I doing wrong? How do I split the passwords in the field? With a comma?

Thanks in advance!

**Comment by solepixel** [comment]
The ACF field is a repeater field, so it's one password for each entry. The original intention of the UI was not designed for 500+ password storage (although it should still work), but you may want to look into using the `wpmp_extra_passwords` filter. Take a look at the first example here: [wpmp_extra_passwords](https://github.com/solepixel/wp-multiple-passwords#filter-wpmp_extra_passwords)

If your passwords are currently in a comma separated form, you'll need to use `explode` to put them into an array then return the array. Let me know if you need any further assistance.

**Comment by jokew** [comment]
Don't know if it worked by replying to the email so again here:

Hi Brian

Okay, my PHP skills are only basic so could I ask you some questions please? If not just let me know, no problem,
The first example you give is the one I need to use right? 

add_filter( 'wpmp_extra_passwords', 'mytheme_extra_string_passwords', 10, 2 );

function mytheme_extra_string_passwords( $extra_passwords, $post ){

    $new_passwords = array(
        'new-password-1',
        'new-password-2',
        'new-password-3'
    );

    $extra_passwords = array_merge( $extra_passwords, $new_passwords );

    return $extra_passwords;
}
But to use it with my passwords I would need to replace the highlighted part with an explode function?
Or just manually type them in there? After the code is ready. Where do I put it? In the functions.php file?

Thanks in advance.

**Comment by jokew** [comment]
Hi Brian

Okay, my PHP skills are only basic so could I ask you some questions please? If not just let me know, no problem,
The first example you give is the one I need to use right?


add_filter( 'wpmp_extra_passwords', 'mytheme_extra_string_passwords', 10, 2 );

function mytheme_extra_string_passwords( $extra_passwords, $post ){

    $new_passwords = array(
        'new-password-1',
        'new-password-2',
        'new-password-3'
    );

    $extra_passwords = array_merge( $extra_passwords, $new_passwords );

    return $extra_passwords;
}

But to use it with my passwords I would need to replace the highlighted part with an explode function?
Or just manually type them in there? After the code is ready. Where do I put it? In the functions.php file?

Thanks in advance.
Kind regards
Joke Wouters

**Comment by solepixel** [comment]
@jokew Depending on how you have your passwords currently will determine how you want to build the function. Yes you want it in functions.php - feel free to replace the "my_theme_" part with something more relevant. Here's an example of what you could do:

```php
add_filter( 'wpmp_extra_passwords', 'mytheme_extra_string_passwords', 10, 2 );

function mytheme_extra_string_passwords( $extra_passwords, $post ){
    if( $post->ID != 999 ) // change 999 to the ID of the post you want to set passwords for.
        return $extra_passwords;

    // if your passwords are stored in a long string, separated by commas, use this:
    $new_passwords = 'new-password-1,new-password-2,new-password-3';
    $new_passwords = explode( ',', $new_passwords );

    // we merge the new array with existing passwords mainly for compatibility with the UI
    $extra_passwords = array_merge( $extra_passwords, $new_passwords );

    return $extra_passwords;
}
```

In this example, we are taking a string of comma separated passwords, converting it into an array, then merging the array with original `$extra_passwords` array, but only when the Post ID is 999 (change the 999 to the ID of the correct post that needs multiple password protection).

Let me know if that helps!

**Comment by jokew** [comment]
Okay, I replaced 'new-password-1,new-password-2,new-password-3'; with the comma separated string of my own passwords. Copied the code into functions.php but unfortunately it doesn't work.
Should I do something else apart from copying the code into functions.php?

By the way, thank you so much for helping me with the code. You're amazing!

**Comment by solepixel** [comment]
Did you change the post ID (999) to match the ID of the page you're trying to password protect?

**Comment by jokew** [comment]
Yes, I did. If 24 is the ID indeed?
![screen shot 2016-09-08 at 14 47 15](https://cloud.githubusercontent.com/assets/22054413/18349833/54f1836e-75d3-11e6-94f2-14f4c90b77b7.png)
The code has be in the functions.php file in the theme folder right?

**Comment by solepixel** [comment]
Yes, functions.php is the right place. Can you send me the WordPress version number you are using? I also made a few tweaks to the plugin, I am checking for valid syntax, skipping empty passwords, and trimming the password values.

Try the latest code I just released 1.0.1. This contains a few checks to prevent possible issues with spaces and invalid passwords (such as non-strings and blank values).

If you're still having trouble, send me your code so I can review how it's implemented. Feel free to remove the actual passwords, but be sure to leave as much intact as possible. Thanks!

**Comment by jokew** [comment]
I'm using Wordpress 4.6.1

`add_filter( 'wpmp_extra_passwords', 'mytheme_extra_string_passwords', 10, 2 );

function mytheme_extra_string_passwords( $extra_passwords, $post ){
    if( $post->ID != 24 ) // change 999 to the ID of the post you want to set passwords for.
        return $extra_passwords;

    // if your passwords are stored in a long string, separated by commas, use this:
    $new_passwords = 'M&WCHMMs,M&WZ0SAw,M&WaU6F\,M&W}/{V>,M&W)Gvfk,M&Wjce@>,M&W)>XsF,M&WfivH5';
    $new_passwords = explode( ',', $new_passwords );

    // we merge the new array with existing passwords mainly for compatibility with the UI
    $extra_passwords = array_merge( $extra_passwords, $new_passwords );

    return $extra_passwords;
}`

This is the code i'm using to test it. Afterwards I will put in all the passwords.
I will install the newest version of your plugin right now!

**Comment by jokew** [comment]
Wow, It worked! I uploaded your new plugin and tested it on a new page and BAM I got in with a password from the code.

Thank you so much! You're amazing!

**Comment by solepixel** [comment]
Great to hear! Not sure what the issue was but I guess something I changed made it work! Let me know if you need anything else!
