### ISSUE TITLE
Content output discrepancies

### ISSUE THREAD

**Issue by noahshrader** [solepixel/wp-multiple-passwords#5]
Seems to be working well! Thanks for working on a plugin for this.

In some cases however, I'm noticing differences in content output. When using the password set in the default password protected box, content created with something like Elementor remains in tact with the proper markup applied to the page. Using any of the custom passwords renders the content on the page, but it kills the Elementor markup. Wasn't sure what might be causing that issue, or if there was a quick fix.

**Comment by solepixel** [comment]
@noahshrader Sorry for the delayed response. I'm not familiar with Elementor, however the way the plugin works is it simply takes a correctly used password and stores it into the WordPress post_password value on the fly, mimicking the core password protected functionality.

So for example, if you have [red, green, blue] passwords, when a user submits the password "orange", it doesn't match any passwords and fails. When a user submits "blue", this "passes" the multi-password check and injects "blue" into the post_password value so when WordPress does it's checks for "blue", they pass and everything else functions the exact same.

So there's really not any content alteration, or even any functionality to handle content rendering. It's sort of just a middle man that spoofs the correct password if it matches one from the multi-password field.

Hope that helps, let me know if I can be of any further assistance.
