### ISSUE TITLE
Invalid password notice

### ISSUE THREAD

**Issue by itchybrain** [solepixel/wp-multiple-passwords#7]
Gday solepixel...I have used the ACF approach (v4.4.12), and multiple passwords are working...thank you :)

My issue is that when I enter an incorrect password, there is no feedback, no error...the input field just returns to being empty.

Have I perhaps got other conflicts occurring, or is it programmed such that there is no feedback supplied to the user?

cheers
Darryl

**Comment by solepixel** [comment]
The way this functionality works in WordPress is:

Password Protect Page
User is prompted for password
If password is correct -> View Page
If password is incorrect -> prompt user, display error

The way the plugin functions is:

Password Protect Page
User is prompted for password
**If password is one of the multiple passwords, the plugin injects the matching correct password into the WordPress functionality, tricking WordPress to thinking this was the correct password, Then the user can view the page**
If password is incorrect -> prompt user, display error - **This functionality does not change. If the password doesn't match any of the stored/multiple passwords, it just lets WordPress handle it however it's supposed to handle it.**

So I would double check to make sure your template is setup correctly to display the error, and make sure no other plugins are conflicting with this functionality. Check your body class to see if it changes and shows some kind of signal that it's supposed to be errored (like password-protected incorrect-password) something like that.

Let me know if I can help further!

**Comment by itchybrain** [comment]
Brian, good lord, you are incredible :) thank you for explaining that so well, and so promptly…I will investigate the potential conflicts…much appreciated!

cheers
 
Darryl
 
Contact details
Darryl Butler
Itchybrain Productions
Mobile: 0403 793 422
Postal:  PO Box 730 
Lavington NSW 2641
darryl@itchybrain.com.au
http://www.itchybrain.com.au
